### ISSUE TITLE
Switch Window Shortcut Listed as as Alt + S instead of Alt + H

### ISSUE THREAD

**Issue by umbrellaid** [darkstego/wakib-keys#12]
https://github.com/darkstego/wakib-keys/blob/114c2e853040cb9c6809f21f8c5cb4a35b8196ef/README.md?plain=1#L110

Switch Window Shortcut Listed as as Alt + S - I assume you changed it at one point to Alt + H or Alt + SHIFT + H

Thank you for your hard work on this project.

**Comment by darkstego** [comment]
Fixed, thank you.
