### ISSUE TITLE
Cursor keys don't work in terminal

### ISSUE THREAD

**Issue by neutvd** [darkstego/wakib-keys#2]
When starting emacs without window system in Linux (Ubuntu 18.04 at least) with `emacs -nw <filename>` the cursor keys print letters. If I disable wakib-keys, the cursor keys work as expected.

**Comment by darkstego** [comment]
I looked into it, and this is an unplanned side effect of using escape to cancel. Turns out terminals code arrow keys using ANSI ESC sequence. So I will likely disable the escape overwriting when used in a terminal.

**Comment by darkstego** [comment]
So it turns out this is a bit trickier than I initially thought. Even without the Escape key mapped, the Arrow key become "M-O A" since M-O is remapped, the arrow keys don't work. A work around for this will take a bit longer than anticipated.

**Comment by neutvd** [comment]
OK. Thank you for the update. I'll just put a guard around the wakib activation and disable it when in terminal. Good luck!

**Comment by darkstego** [comment]
Finally found an approach that was clean and seems to do the trick. Latest version should have arrow keys working for movement.

**Comment by neutvd** [comment]
Just tested. Confirmed it works. Thank you!

**Comment by darkstego** [comment]
There was another update that fixes the behavior of the arrow keys. You will notice that while the arrow keys work, if you traverse shorter lines while moving vertically using arrow keys, that the column moves to the shorter line. The latest commit fixes that.
