### ISSUE TITLE
Typing "<" goes to the minibuffer

### ISSUE THREAD

**Issue by lucasemmoreira** [darkstego/wakib-keys#5]
Hi there! nice lib you have here!

I have just installed and I noticed something. I cannot type "<". Emacs waits for another key to complete a shortcut. 
Pretty much, pops the "<" in the minibuffer the same way when you type "C-c" in default emacs setting.

I took a quick a look at your code but I did not find anything that seems to reserve the lesser sign ("<")

**Comment by darkstego** [comment]
Was able to fix it, latest version should work now.
